### PR TITLE
fix(`EIP712`): `chainId` should support `uint256` values

### LINKED ISSUE #256: EIP712 - Cannot pass a string as `chainId`
### Describe the bug

Currently the `TypedDataDomain` looks like this:

```
export type TypedDataDomain = {
  chainId?: number | undefined
  name?: string | undefined
  salt?: ResolvedRegister['bytesType']['outputs'] | undefined
  verifyingContract?: Address | undefined
  version?: string | undefined
}
```

Sometimes the `chainId` might be larger than a `number`, so I was wondering whether it would be possible to also support `string` and `bigint` (or maybe just `string`) for that field. [In the spec](https://eips.ethereum.org/EIPS/eip-712#definition-of-domainseparator) the attribute is expected to be an `uint256`.

I have seen in another "famous library" (:p) that the type for `chainId` is `number | bigint | string | null`.

Thanks in advance.

### Expected Behavior

I can pass a `string` as `chainId`. Specifically, I would like to be able to pass these values:

1. `14018334920824264832118464179726739019961432051877733167310318607178`
2. `1176455790972829965191905223412607679856028701100105089447013101863`
3. `20257036855429895315704288894496386224204271168750785572924599986678`

### Link to Minimal Reproducible Example

_No response_

### Steps To Reproduce

_No response_

### Package Version

1.0.6

### TypeScript Version

5.6.3

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/abitype/issues) for the bug I encountered.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by freemanzMrojo**
Since the largest integer that a `number` could safely represent in TypeScript is 2^53 - 1, bigger values that are supported by `uint256` cannot fit into it (some sample values in the issue).

Closes #256

---

## PR-Codex overview
This PR focuses on updating the `TypedDataDomain` type to allow the `chainId` property to accept `bigint` values in addition to `number`, enhancing flexibility for handling larger numeric values.

### Detailed summary
- Updated `chainId` in `TypedDataDomain` type to accept `bigint` in `packages/abitype/src/abi.ts`.
- Modified `chainId` in `TypedDataDomain` Zod schema to allow `bigint` in `packages/abitype/src/zod.ts`.

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

File: packages/abitype/src/abi.ts [hunk 1]
```diff
@@ -218,7 +218,7 @@ export type Abi = readonly (
 // Typed Data Types
 
 export type TypedDataDomain = {
-  chainId?: number | undefined
+  chainId?: number | bigint | string | undefined
```
Comment (tmm) [inline packages/abitype/src/abi.ts:221]:
```suggestion
  chainId?: number | bigint | undefined
```

File: packages/abitype/src/zod.ts [hunk 2]
```diff
@@ -299,7 +299,7 @@ export const Abi = z
 // Typed Data Types
 
 export const TypedDataDomain = z.object({
-  chainId: z.number().optional(),
+  chainId: z.union([z.number(), z.string(), z.bigint()]).optional(),
```
Comment (tmm) [inline packages/abitype/src/zod.ts:302]:
```suggestion
  chainId: z.union([z.number(), z.bigint()]).optional(),
```

**Review by tmm — CHANGES_REQUESTED** [review]
